---
- name: Prepare environment for upload to SFS in patch scan playbook
  hosts: all
  connection: local
  gather_facts: false
  run_once: true
  ignore_unreachable: true
  tasks:
    - include_role:
        name: sfs_upload
      vars:
        sfs_upload_stage: "prepare"
        output_dir: "/tmp/testing_sfs"

    - name: Stop execution if SFS failed
      delegate_to: localhost
      delegate_facts: true
      set_fact:
        myrole_run_execution: true
      when: returncode == "0"
      
      
- hosts: all
  become: True
  become_method: sudo
  gather_facts: false
  ignore_unreachable: true
  ignore_errors: true
  roles:
    - migration_precheck
    
    
- name: Upload data to SFS and report SFS return value as my result.
  hosts: all
  connection: local
  gather_facts: false
  run_once: true
  ignore_unreachable: true
  tasks:
    - include_role:
        name: sfs_upload
      vars:
        sfs_upload_stage: "upload"
        output_file_name: "unix_precheck_{{ tower_job_id }}_{{ hostvars.localhost.timestamp }}.zip"
        merged_file_name: "unix_precheck_consolidated_{{ tower_job_id }}_{{ hostvars.localhost.timestamp }}.txt"
        merge_results: true       
      when:
        - hostvars.localhost.myrole_run_execution is defined
        - hostvars.localhost.myrole_run_execution        
